### ISSUE TITLE
踩坑记录

### ISSUE THREAD

**Issue by boogunote** [HaxyMoly/Vicuna-LangChain#2]
pip install --pre torch==2.1.0.dev20230415+cu118 torchvision==0.16.0.dev20230415+cu118 torchaudio==2.1.0.dev20230415+cu118 -f https://download.pytorch.org/whl/nightly/cu118/torch_nightly.html

```
python vicuna_cli.py --vicuna-dir "xxx\real-vicuna" --num-gpus 2 --knowledge-base
```

fast-chat 到这个 commit
5ccf84218f1a0d4c7c50bef043a200ad36576cdc    

新建 static 文件夹

增加 shibing624/text2vec-base-chinese ，增加 shibing624

**Comment by HaxyMoly** [comment]
非常感谢您的分享。目前已经修复了对最新版本FastChat的支持，以及torch版本和hibing624/text2vec-base-chinese路径问题
