### ISSUE TITLE
vicuna_cli.py num-gpus type should be int, not str

### ISSUE THREAD

**Issue by wangrui6** [HaxyMoly/Vicuna-LangChain#4]
As indicated, if it's kept as str, then the code will complain

`'<' not supported between instances of 'int' and 'str'`

Ref:
https://github.com/HaxyMoly/Vicuna-LangChain/blob/66799aad611907e065169f8215cf80cabf60ee0f/vicuna_cli.py#L69

**Comment by HaxyMoly** [comment]
Thanks for your feedback. I just realized that the latest version of FastChat now accepts the argument "num_gpus" as an integer instead of a string. The issue has been fixed.
